# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0014_auto_20181017_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundRelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A unique name to identify this relayhost/auth combination', max_length=100, unique=True, verbose_name='name')),
                ('relayhost', models.CharField(db_index=True, max_length=254)),
                ('is_default_for_all_senders', models.BooleanField(default=True, help_text='Check to activate this domain', verbose_name='is default for all senders')),
                ('use_tls', models.BooleanField(default=True, help_text='Check to make this connection use tls', verbose_name='use_tls')),
                ('tls_cafile', models.CharField(max_length=254)),
                ('auth_required', models.BooleanField(default=True, help_text='Check to make this connection always use authentication', verbose_name='Authentication is required')),
                ('username', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=512, verbose_name='password')),
                ('client_cert', models.CharField(max_length=512, verbose_name='client certificate')),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('view_outboundrelay', 'View outbound relay'), ('view_outboundrelays', 'View outbound relay')),
            },
        ),
    ]
